### ISSUE TITLE
[FR] Adding Mosquitto as a separate chart with a dependency

### ISSUE THREAD

**Issue by NigelVanHattum** [Koenkk/zigbee2mqtt-chart#2]
Since Mosquitto is mentioned as the default MQTT broker for Z2M in the getting started docs. 

Could we perhaps add a new chart for Mosquitto and add that as a dependency to the main chart? If wanted, I could try to work on this

**Comment by jlpedrosa** [comment]
Actually if you go to the mosquitto GH, there's already a PR to create the chart.

**Comment by NigelVanHattum** [comment]
Just linking it here, so we can add the dependency once it's merged and released.

[Initial Helm Chart implementation #3036](https://github.com/eclipse/mosquitto/pull/3036)

**Comment by jlpedrosa** [comment]
Honestly I would not add the dependency here, technically you can use different MQTT implementations not just mosquito. I Would also not pull home assistant into this chart. It also forces to release new versions of this chart when mosquitto is updated. I don't mind adding some examples if it becomes an official chart. But personally I don't think it's a good idea to try to create an stack out of this chart.

**Comment by pmarques** [comment]
I share @jlpedrosa's opinion.

**Comment by NigelVanHattum** [comment]
Makes sense, I was suggesting it since the docs clearly mention it.
